application: youforrexapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: web/static
  application_readable: true

- url: /cron
  script: web.pages.symbolGraph.app

- url: /croncheck
  script: web.pages.checkAlert.app

- url: /
  script: web.pages.base.app

- url: /support
  script: web.pages.support.app

- url: /risk
  script: web.pages.risk.app

- url: /UpdatePass
  script: web.pages.UpdatePass.app

- url: /forgetPass
  script: web.pages.forgetPass.app

- url: /history
  script: web.pages.history.app

- url: /register
  script: web.pages.register.app

- url: /login
  script: web.pages.login.app

- url: /logout
  script: web.pages.logout.app

- url: /alert
  script: web.pages.alert.app

- url: /about
  script: web.pages.about.app

- url: /home
  script: web.pages.home.app

- url: /deleteROW
  script: web.pages.deleteROW.app

- url: /deleteROWAL
  script: web.pages.deleteROWAL.app

- url: /editROW
  script: web.pages.editRow.app

- url: /editROWAL
  script: web.pages.editROWAL.app

- url: /imageView
  script: web.pages.imageView.app

- url: /handlerImage
  script: web.pages.handlerImage.app

- url: /error_page
  script: web.pages.error_page.app



- url: /(.*)
  script: web.pages.home.app


libraries:
- name: webapp2
  version: "2.5.2"
